import { OpenAPIHono, createRoute, z } from '@hono/zod-openapi';
import { ParseRequestSchema, ParseResponseSchema } from '@/schemas';
import { parseSVG } from '@/lib/svg/parser';

const parse = new OpenAPIHono();

const parseRoute = createRoute({
  method: 'post',
  path: '/',
  tags: ['Parse'],
  summary: 'Parse SVG to extract LaTeX',
  description: 'Extract LaTeX equations and metadata from an SVG generated by this API. Supports both JSON (`application/json`) with svg field and direct SVG content (`image/svg+xml` or `text/plain`). You can pipe SVG directly: `cat image.svg | curl -X POST <url> -H "Content-Type: image/svg+xml"`',
  request: {
    body: {
      content: {
        'application/json': {
          schema: ParseRequestSchema,
        },
        'image/svg+xml': {
          schema: z.string().openapi({
            example: '<svg>...</svg>',
            description: 'SVG content directly as image/svg+xml',
          }),
        },
        'text/plain': {
          schema: z.string().openapi({
            example: '<svg>...</svg>',
            description: 'SVG content as plain text',
          }),
        },
      },
    },
  },
  responses: {
    200: {
      description: 'Parse result',
      content: {
        'application/json': {
          schema: ParseResponseSchema,
        },
      },
    },
    400: {
      description: 'Invalid SVG or missing content',
      content: {
        'application/json': {
          schema: ParseResponseSchema,
        },
      },
    },
  },
});

parse.openapi(parseRoute, async (c) => {
  const contentType = c.req.header('Content-Type') || 'application/json';

  let svg: string;

  // Handle direct SVG input (image/svg+xml or text/plain)
  if (contentType.includes('image/svg+xml') || contentType.includes('text/plain')) {
    svg = await c.req.text();

    if (!svg || svg.trim() === '') {
      return c.json(
        {
          success: false,
          hasMetadata: false,
          equations: [],
          errors: ['SVG content is required'],
        },
        400
      );
    }
  } else {
    // Handle JSON input
    const body = c.req.valid('json') as { svg: string };
    svg = body.svg;
  }

  const result = parseSVG(svg);

  return c.json({
    success: result.errors.length === 0,
    hasMetadata: result.hasMetadata,
    metadata: result.metadata,
    equations: result.equations,
    errors: result.errors,
  });
});

export default parse;
